"""empty message

Revision ID: 1095d25c421e
Revises: 7692f6adc84b
Create Date: 2023-08-21 06:57:02.148644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1095d25c421e'
down_revision = '7692f6adc84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('user_email', sa.String(length=120), nullable=True))
    op.drop_column('flags', 'user_id')
    op.add_column('uservariable', sa.Column('user_email', sa.String(length=128), nullable=False))
    op.drop_column('uservariable', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uservariable', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('uservariable', 'user_email')
    op.add_column('flags', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('flags', 'user_email')
    # ### end Alembic commands ###
