"""empty message

Revision ID: 5ea5b2300b51
Revises: 8c43b4427489
Create Date: 2023-08-17 09:26:40.520266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ea5b2300b51'
down_revision = '8c43b4427489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uservariable', sa.Column('variable_value', sa.String(length=100), nullable=True))
    op.drop_column('uservariable', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uservariable', sa.Column('value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_column('uservariable', 'variable_value')
    # ### end Alembic commands ###
