"""empty message

Revision ID: 7692f6adc84b
Revises: 5ea5b2300b51
Create Date: 2023-08-18 14:38:02.304631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7692f6adc84b'
down_revision = '5ea5b2300b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uservariable_ibfk_1', 'uservariable', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('uservariable_ibfk_1', 'uservariable', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
